Changelogs
JakeDaBoss/Novis-Station pull request #24
Opened 2016-10-02 10:40 UTC by JakeDaBoss

- Changelog update.

2016-10-02 10:41 UTC, JakeDaBoss commented
Someone review please.

2016-10-02 14:04 UTC, BlueNexus requested changes

2016-10-02 14:04 UTC, BlueNexus commented on html/changelogs/.all_changelog.yml
> +  N3X15:
I don't recall N3X15 working on this repo.

2016-10-02 14:11 UTC, JakeDaBoss commented on html/changelogs/.all_changelog.yml
> +  N3X15:
I had to make Lyka's, okay? :/

2016-10-02 14:13 UTC, JakeDaBoss commented
Done @BlueNexus

2016-10-03 07:34 UTC, BlueNexus approved these changes

2016-10-03 07:36 UTC, BlueNexus commented
I suggest asking #codershuttle about using qdel instead of del, before this is merged.

2016-10-03 07:38 UTC, BlueNexus requested changes

2016-10-03 07:38 UTC, BlueNexus commented on code/modules/admin/verbs/admincryo.dm
> +								O.owner.current << "\red You get the feeling your target is no longer within your reach. Time for Plan [pick(list("A","B","C","D","X","Y","Z"))]..."
Depreciated. Changed \red to ```<span class="warning">```

2016-10-03 07:38 UTC, BlueNexus commented on code/modules/admin/verbs/admincryo.dm
> +				message_admins("\blue [key_name_admin(usr)] has admin cryoed [key_name(M)]")
Ditto

2016-10-03 07:43 UTC, JakeDaBoss commented
I'll fix this this afternoon.

2016-10-03 13:13 UTC, JakeDaBoss commented
@BlueNexus Always use qdel.

2016-10-03 16:46 UTC, BlueNexus commented
Please correct all instances of del, then.

2016-10-03 20:20 UTC, JakeDaBoss commented
Fixes #27

2016-10-04 20:12 UTC, closed without merging