Oliver test branch
JakeDaBoss/Novis-Station pull request #4
Opened 2016-09-23 22:30 UTC by JakeDaBoss

This is a semi-ready base of the map and base jobs. Needs to be expanded on, and NOT ready for use!

2016-09-23 22:34 UTC, BlueNexus commented on code/game/objects/items/weapons/cards_ids.dm
>  /obj/item/weapon/card/id/medical/geneticist
This should be changed to ```/obj/item/weapon/card/id/medical/medicalexam```

2016-09-23 22:35 UTC, BlueNexus commented on code/modules/clothing/gloves/miscellaneous.dm
> +	item_state = "swat_gl"
Remove the extra swat gloves, this is a duplicate of line 54 to 57.

2016-09-23 22:36 UTC, BlueNexus requested changes

2016-09-23 22:38 UTC, JakeDaBoss commented
I'll do it tomorrow.

2016-09-24 13:56 UTC, BlueNexus approved these changes

2016-09-24 13:57 UTC, merged