Fixes and additions.
JakeDaBoss/Novis-Station pull request #50
Opened 2016-10-09 14:59 UTC by JakeDaBoss

Nerfs, tweaks, fixes, the usual.

2016-10-09 15:05 UTC, BlueNexus commented on code/_helpers/logging.dm
> +		diary << "\[[time_stamp()]]DEVSAY: [text][log_end]"
This should follow the same format as the other logs. 
```
game_log("DEVSAY", text)
```

2016-10-09 15:06 UTC, BlueNexus commented on html/changelogs/JakeDaBoss.yml
> +  - tweak: "Nerfed taser bolt's HALLOSS agony from 80 to 50."
Players won't know what HALLOSS means. Changelogs should be phrased in a way that normal players can understand.

2016-10-09 15:06 UTC, BlueNexus commented on code/modules/admin/verbs/sendfax.dm
> +		usr<< "\red The fax is broken or has no power!"
Bad usage of \red

2016-10-09 15:08 UTC, BlueNexus commented on code/modules/admin/verbs/adminsay.dm
> +		C << "<span class='dev_channel'>" + create_text_tag("dev", "DEV:", C) + " <span class='name'>[sender_name]</span>(<A HREF='?src=\ref[C.holder];adminplayerobservejump=\ref[mob]'>JMP</A>): <span clas
This should follow the same format as mod_say and admin_say.

2016-10-09 15:08 UTC, ghost requested changes

2016-10-09 15:08 UTC, Lykayos commented on code/modules/admin/admin_verbs.dm
>  	/client/proc/cmd_admin_subtle_message
Missing your comma here. Don't want to trigger the wonders of syntax errors.

2016-10-09 15:08 UTC, Lykayos commented on code/modules/admin/verbs/sendfax.dm
> +		usr<< "\red The fax is broken or has no power!"
Needs updated to span classes.

2016-10-09 15:08 UTC, Lykayos commented on code/modules/projectiles/projectile/energy.dm
> +	agony = 50
More of an opinion but this makes stun revolvers useless. They have a far slower fire rate, lack the ability to pass through objects, take up more space, have slow projectiles, and very few shots to a clip. Add in the fact that with this edit they hardly do more pain than a normal taser and there's no reason to bother with them anymore.

2016-10-09 15:10 UTC, BlueNexus commented
You have two reviews: Resolve them both.

2016-10-09 15:10 UTC, JakeDaBoss commented on code/modules/admin/admin_verbs.dm
>  	/client/proc/cmd_admin_subtle_message
aaaashit.

2016-10-09 15:10 UTC, JakeDaBoss commented on code/modules/projectiles/projectile/energy.dm
> +	agony = 50
This also goes for the stun e-gun.

2016-10-09 15:11 UTC, Lykayos commented
I like how our reviews happened within ten seconds of each other.

2016-10-09 15:12 UTC, ghost commented on code/modules/projectiles/projectile/energy.dm
> +	agony = 50
Also as a note this is the projectile for the stun shotgun as well.

2016-10-09 15:17 UTC, BlueNexus commented
I need confirmation that this will compile and pass bay's unit tests. I'm not convinced at the moment.

2016-10-09 15:18 UTC, Lykayos commented on code/modules/projectiles/projectile/energy.dm
> +	agony = 50
The stun egun uses the /obj/item/projectile/beam/stun
This is the projectile for the research acquired stun revolver and the stun shells for the shotguns

2016-10-09 15:20 UTC, JakeDaBoss commented on code/modules/projectiles/projectile/energy.dm
> +	agony = 50
I'll cut some middle ground, make it 65.

2016-10-09 15:21 UTC, Lykayos commented on code/modules/projectiles/projectile/energy.dm
> +	agony = 50
What I'm saying is this isn't even the taser you edited.

2016-10-09 15:21 UTC, Lykayos commented on code/modules/projectiles/projectile/energy.dm
> +	agony = 50
Unless someone messed up the taser.

2016-10-09 15:22 UTC, ghost commented on code/modules/projectiles/projectile/energy.dm
> +	agony = 50
No just checked the taser is /beam/stun aswell

2016-10-09 15:27 UTC, BlueNexus requested changes

2016-10-09 15:27 UTC, BlueNexus commented on code/modules/admin/verbs/adminsay.dm
> +		C << "<span class='dev_channel'>" + create_text_tag("dev", "DEV:", C) + " <span class='name'>[sender_name]</span>([admin_jump_link(mob, C.holder)]): <span class='message'>[msg]</span></span>"
That's not what I meant. This section shouldn't be here. Look at how mod and adminsay does it.

2016-10-09 15:27 UTC, BlueNexus commented on code/modules/projectiles/projectile/energy.dm
> +	agony = 65
This still doesn't apply to taser stun or egun stun mode.

2016-10-09 15:29 UTC, JakeDaBoss commented on code/modules/projectiles/projectile/energy.dm
> +	agony = 65
It apparantly does. We tested it. This goes for e-gun stun mode. It got Kaed down in one shot on 80.

2016-10-09 15:31 UTC, Lykayos commented on code/modules/admin/verbs/sendfax.dm
> +		usr<< "<span class='warning'> The fax is broken or has no power!"
Close the span class too. ;-;

2016-10-09 15:35 UTC, BlueNexus commented on code/modules/admin/verbs/adminsay.dm
>  	feedback_add_details("admin_verb","MS") //If you are copy-pasting this, ensure the 2nd parameter is unique to the new proc!
UUUGH
Lines 44 to 39 shouldn't be here, is what I'm trying to say.

2016-10-09 15:36 UTC, Lykayos commented on code/modules/projectiles/projectile/energy.dm
> +	agony = 65
/obj/item/weapon/gun/energy/gun
	name = "energy gun"

[. . . ]

	projectile_type = /obj/item/projectile/beam/stun
	origin_tech = list(TECH_COMBAT = 3, TECH_MAGNET = 2)
	modifystate = "energystun"

	firemodes = list(
		list(mode_name="stun", projectile_type=/obj/item/projectile/beam/stun, modifystate="energystun"),
		list(mode_name="lethal", projectile_type=/obj/item/projectile/beam, modifystate="energykill"),
		)

2016-10-09 16:24 UTC, JakeDaBoss commented on code/modules/projectiles/projectile/energy.dm
> +	agony = 50
What projectile does that use then?

2016-10-09 16:32 UTC, Lykayos commented on code/modules/projectiles/projectile/energy.dm
> +	agony = 50
/obj/item/projectile/beam/stun
Which deals 40 pain and downs someone in an average of three shots not counting armor.
Unless you headshot them, in that case it's around 2

2016-10-10 12:07 UTC, BlueNexus commented
Confirm this compiles?

2016-10-10 20:44 UTC, JakeDaBoss commented
@BlueNexus 
https://4stor.com/uwIT4
https://4stor.com/7mGuO

2016-10-10 20:48 UTC, BlueNexus commented
Have these features been tested in their current state, especially devsay?

2016-10-10 20:50 UTC, JakeDaBoss commented
Not yet. I can check tomorrow. How do I squash again, or you got a ref page for me?

2016-10-10 21:21 UTC, BlueNexus commented
```
git rebase -i HEAD~[number of commits to squash]
```
Then change the "pick" beside each commit UNDER the top one to "s"
press [esc] [:wq] [enter]
Press [esc] [:wq] [enter] again on the next screen
then
```
git push -f origin Oliver-test-branch:Oliver-test-branch
```

2016-10-12 20:39 UTC, JakeDaBoss commented
@BlueNexus

2016-10-12 20:40 UTC, JakeDaBoss commented
Can't be squashed. My updates are too erratic. Code and map.

2016-10-12 22:45 UTC, BlueNexus requested changes
Please ensure that mapmerge is used. A 2500 add/remove diff is unacceptable.

2016-10-12 22:59 UTC, JakeDaBoss commented
And you want me to do that post-edit now? This contains some pretty wanted fixes. This has been up for 3 days.

-------- Oorspronkelijk bericht --------
Van: BlueNexus <notifications@github.com>
Datum: 13-10-2016  00:45  (GMT+01:00)
Aan: JakeDaBoss/Novis-Station <Novis-Station@noreply.github.com>
Cc: Jake Miles <visiongamingjake@hotmail.com>, Author <author@noreply.github.com>
Onderwerp: Re: [JakeDaBoss/Novis-Station] Fixes and additions. (#50)

BlueNexus requested changes on this pull request.

Please ensure that mapmerge is used. A 2500 add/remove diff is unacceptable.



--
You are receiving this because you authored the thread.
Reply to this email directly or view it on GitHub:
https://github.com/JakeDaBoss/Novis-Station/pull/50#pullrequestreview-3977150

2016-10-13 06:50 UTC, JakeDaBoss commented
@bluenexus

I suggest merging this and stop nitpicking every detail. I'll work mapmerge in the next update to make the diff lesser.

It's seriously aggravating with how slow this goes, as I get all the questions how the update is coming.

2016-10-13 11:04 UTC, BlueNexus commented
Using mapmerge is standard practice, I expected you to _know_ to do it.

2016-10-13 11:26 UTC, BlueNexus commented on code/modules/projectiles/projectile/energy.dm
> +	agony = 65
@JakeDaBoss The energy gun and taser don't _use_ /obj/item/projectile/energy/electrode/stunshot.

2016-10-13 12:11 UTC, JakeDaBoss commented
It won't be squashed. I'll take a look at the rest.

2016-10-13 15:15 UTC, JakeDaBoss commented
@BlueNexus just merge it. I'm not squashing it, considering my commits can't be squashed.

2016-10-13 16:21 UTC, BlueNexus commented
@jakedaboss I can't merge it while there are outstanding requested changes.

2016-10-13 16:25 UTC, JakeDaBoss commented
Which are @bluenexus

2016-10-13 18:50 UTC, ghost approved these changes

2016-10-13 20:45 UTC, BlueNexus approved these changes

2016-10-13 20:50 UTC, merged