Oliver test branch
JakeDaBoss/Novis-Station pull request #6
Opened 2016-09-29 22:46 UTC by JakeDaBoss

Major fixes across the board.

More in the commit history.

2016-09-29 22:46 UTC, JakeDaBoss commented
@BlueNexus

2016-09-30 07:50 UTC, BlueNexus requested changes

2016-09-30 07:50 UTC, BlueNexus commented on baystation12.int
>  // END_INTERNALS
Revert all changes to this file, so remove lines 3, 4, 8 and 9.

2016-09-30 07:50 UTC, BlueNexus commented
You should also properly port changes, rather than committing them as your own.

2016-09-30 07:56 UTC, JakeDaBoss commented
Not exactly sure how to pull singular commits into our repo.

2016-09-30 08:09 UTC, BlueNexus commented
You would cherry-pick them, but I doubt you know how to do that. This will do for now, once the requested change is done.

2016-09-30 14:02 UTC, JakeDaBoss commented
Done @BlueNexus

2016-09-30 14:54 UTC, BlueNexus approved these changes

2016-09-30 14:54 UTC, merged